version: '3.7'

services:
  mocka-backend:
    build: mocka-backend/
    container_name: mocka-backend
    ports:
      - "8080:8080"
    depends_on:
      - minio
      - mongo
  mongo-express:
    # dev tool
    image: mongo-express:1.0.0-alpha
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/
    ports:
      - "8081:8081"
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0.5-jammy
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - "${MONGO_DATA_DIR}:/data/db"
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "9001:9001"
    volumes:
      - "${MINIO_DATA_DIR}:/data"
