version: '3.7'

services:
  mocka-frontend:
    build: mocka-frontend/
    container_name: mocka-frontend
    ports:
      - "80:80"
    depends_on:
      - mocka-backend
  mocka-backend:
    build: mocka-backend/
    container_name: mocka-backend
    depends_on:
      - minio
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "9001:9001"
    volumes:
      - "${MINIO_STORAGE_DIR}:/data"
