version: '3.7'

services:
  mocka-frontend:
    build: mocka-frontend/
    container_name: mocka-frontend
    ports:
      - "80:80"
    depends_on:
      - mocka-backend
  mocka-backend:
    build: mocka-backend/
    container_name: mocka-backend
    depends_on:
      - mongo-initializer
      - minio
  mongo-initializer:
    build: mongo-initializer/
    container_name: mongo-initializer
    network_mode: container:mongo
    environment:
      - MONGO_RS_ID=rs0
      - MONGO_RS_HOST=mongo:27017
      - MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0.5-jammy
    container_name: mongo
    command: mongod --auth --keyFile /keyfile --replSet rs0 --bind_ip localhost,mongo
    environment:
      - MONGO_INITDB_DATABASE=mocka
    volumes:
      - "${MONGO_DATA_DIR}:/data/db"
      - "${MONGO_KEYFILE}:/keyfile"
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - "${MINIO_DATA_DIR}:/data"
