version: '3.7'

services:
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER-admin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD-password}
    ports:
      - "9000:9000"
      - "9001:9001"
