spring.application.name: mocka-backend
server.port: 8080

minio:
  endpoint: http://minio:9000
  credentials:
    accessKey: mocka-backend
    secretKey: mocka-backend

logging:
  level:
    root: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.mocka: TRACE