spring:
  application.name: mocka-backend
  main.banner-mode: off

server:
  port: 8080
  forward-headers-strategy: NATIVE

api-info:
  title: Mocka API
  description: The RESTful API mocking service. User API documentation.
  version: @project.version@

minio:
  endpoint: http://minio:9000
  credentials:
    accessKey: minioadmin
    secretKey: minioadmin

cors:
  allowed-origins:
    - http://localhost
    - http://mocka.local
    - http://mocka.org
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE

storage:
  bucket: scripts
  verify-connection-on-startup: true
  verify-connection-on-calls: false

script-engine:
  version: es6

logging:
  level:
    root: INFO
    org.mocka: DEBUG
